# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-21 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_remove_trip_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='operating_hours',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='review',
        ),
    ]
